In [1]:
import pandas as pd
import numpy as np

from pandas_datareader.data import DataReader
from datetime import datetime

import matplotlib.pyplot as plt

# get preprocessed data

In [2]:
data_sentim_ana = pd.read_csv('2.tesla_data_dates_sentiment_analysis.csv')
data_sentim_ana

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num,Dtime,date,cleaned_text,Subjuctivity,Polarity,Class_sentiment_negative,Class_sentiment_neutral,Class_sentiment_positive
0,550442977802207232,ShowDreamCar,1420070807,$GM $TSLA: Volkswagen Pushes 2014 Record Recal...,0,0,1,2015-01-01 01:06:47,2015-01-01,gm tsla volkswagen pushes record recall tally...,0.500000,0.250000,0,0,1
1,550443807834402816,i_Know_First,1420071005,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,2015-01-01 01:10:05,2015-01-01,swing trading return days swingtrading forec...,0.000000,0.000000,0,1,0
2,550443808606126081,aaplstocknews,1420071005,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,2015-01-01 01:10:05,2015-01-01,swing trading return days swingtrading forec...,0.000000,0.000000,0,1,0
3,550443809700851716,iknowfirst,1420071005,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,2015-01-01 01:10:05,2015-01-01,swing trading return days swingtrading forec...,0.000000,0.000000,0,1,0
4,550443857142611968,Cprediction,1420071016,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,2015-01-01 01:10:16,2015-01-01,swing trading return days swingtrading forec...,0.000000,0.000000,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1096863,1212158772015034369,StockJoke,1577836146,"I'm getting wasted on NYE, and thanks to @NHTS...",0,0,0,2020-01-01 00:49:06,2020-01-01,im getting wasted nye thanks approved tsla aut...,0.100000,0.000000,0,1,0
1096864,1212159099632267268,sweetog76,1577836224,$TSLA Very Interesting dude:,0,0,0,2020-01-01 00:50:24,2020-01-01,tsla interesting dude,0.500000,0.500000,0,0,1
1096865,1212159184931717120,MelaynaLokosky,1577836245,If only 2020 brought more self-awareness to Te...,0,1,0,2020-01-01 00:50:45,2020-01-01,brought selfawareness tesla autopilot asshole...,0.000000,0.000000,0,1,0
1096866,1212159838882533376,ShortingIsFun,1577836401,In 2020 I may start Tweeting out positive news...,0,0,1,2020-01-01 00:53:21,2020-01-01,may start tweeting positive news xom cvx mcep...,0.472727,-0.036364,1,0,0
1096867,1212160015332728833,Commuternyc,1577836443,Patiently Waiting for the no twitter sitter tw...,0,0,5,2020-01-01 00:54:03,2020-01-01,patiently waiting twitter sitter tweets tsla t...,0.000000,0.000000,0,1,0

# calculate the sum of feature like, comment, retweet

In [3]:
tl0 = data_sentim_ana['like_num'][data_sentim_ana['date']==data_sentim_ana.date[93]].sum() # date 01-01-2015 starts
tl1 = data_sentim_ana['like_num'][data_sentim_ana['date']==data_sentim_ana.date[94]].sum() # date 02-01-2015 starts
tl0,tl1

(87, 136)

In [4]:
data_smedia_sum = data_sentim_ana.groupby(data_sentim_ana.date).sum()
data_smedia_sum.head()

,tweet_id,post_date,comment_num,retweet_num,like_num,Subjuctivity,Polarity,Class_sentiment_negative,Class_sentiment_neutral,Class_sentiment_positive
date,,,,,,,,,,
2015-01-01,5.175966e+19,133490951098,23,42,87,30.276263,12.192172,15,44,35
2015-01-02,1.113077e+20,286882492028,43,51,136,58.117857,24.628968,25,102,75
2015-01-03,4.962337e+19,127826282034,10,25,89,19.596165,6.015433,6,58,26
2015-01-04,6.620679e+19,170445126534,11,35,75,21.760570,7.227273,9,81,30
2015-01-05,1.523821e+20,392049185482,23,80,201,78.210868,36.700063,17,148,111

#### calculate the total number of tweetts per day then sum it with the sum of re tweet for that day

In [5]:
twt_ct_per_day = data_sentim_ana.date.groupby(data_sentim_ana.date).count()
twt_ct_per_day.values

array([  94,  202,   90, ..., 1358, 1126,   14], dtype=int64)

In [6]:
data_smedia_sum['tweet_count'] = twt_ct_per_day.values
data_smedia_sum

,tweet_id,post_date,comment_num,retweet_num,like_num,Subjuctivity,Polarity,Class_sentiment_negative,Class_sentiment_neutral,Class_sentiment_positive,tweet_count
date,,,,,,,,,,,
2015-01-01,5.175966e+19,133490951098,23,42,87,30.276263,12.192172,15,44,35,94
2015-01-02,1.113077e+20,286882492028,43,51,136,58.117857,24.628968,25,102,75,202
2015-01-03,4.962337e+19,127826282034,10,25,89,19.596165,6.015433,6,58,26,90
2015-01-04,6.620679e+19,170445126534,11,35,75,21.760570,7.227273,9,81,30,120
2015-01-05,1.523821e+20,392049185482,23,80,201,78.210868,36.700063,17,148,111,276
...,...,...,...,...,...,...,...,...,...,...,...
2019-12-28,7.858624e+20,1023818090382,688,900,5253,235.425825,62.305687,112,227,310,649
2019-12-29,7.655246e+20,997058988274,673,839,6425,218.909844,42.348362,130,243,259,632
2019-12-30,1.645430e+21,2142539040171,1494,2201,13014,479.708670,111.280921,235,508,615,1358
2019-12-31,1.364695e+21,1776596925479,936,1086,9674,397.183524,100.569139,193,453,480,1126
2020-01-01,1.697017e+19,22089693639,5,2,19,6.353896,2.944098,1,3,10,14

In [8]:
total = []
count = 0
for i in data_smedia_sum.index:
        total.append(data_smedia_sum['tweet_count'][i] + data_smedia_sum['retweet_num'][i])
        print(data_smedia_sum['tweet_count'][i] + data_smedia_sum['retweet_num'][i])

136
253
115
155
356
271
317
287
320
159
74
589
880
1180
433
425
152
214
120
313
423
457
388
123
93
251
277
251
334
285
113
131
297
351
308
328
1244
173
219
397
689
1963
2575
703
589
438
399
557
303
542
637
237
197
658
547
382
686
364
163
138
602
523
420
388
487
316
166
620
471
451
329
571
254
300
1485
429
688
1221
555
286
239
273
342
537
347
702
214
314
1564
865
1371
531
366
213
224
1340
429
882
459
338
883
215
294
404
317
248
295
130
135
497
511
979
454
492
244
175
935
585
424
874
1912
463
100
621
923
1737
1313
530
516
178
529
170
458
489
1000
309
279
579
162
393
591
446
123
47
222
333
364
544
423
271
321
388
360
353
346
457
94
307
640
665
569
384
456
62
212
473
353
543
488
382
230
233
548
452
417
513
369
219
299
512
440
345
982
309
278
129
276
622
609
299
414
208
205
183
607
613
402
845
188
98
559
799
379
137
287
215
125
282
412
253
1120
912
201
266
461
318
1917
705
658
148
210
545
430
472
944
1552
241
162
1178
453
526
437
392
161
108
431
326
447
803
645
290
235
415
371
417
441
389
92
117
182
320
398
321
351
107
88
266
368
360
441
352
258
276
700
437
338
438
474
172
295
603
585
1073
562
581
170
190
462
470
589
484
948
184
113
494
511
529
585
512
177
221
345
1728
622
361
368
211
126
261
435
446
358
394
159
223
536
1569
1043
335
337
303
159
279
326
339
250
301
113
211
396
264
312
305
733
155
187
220
316
496
197
224
180
193
371
405
434
270
320
142
120
340
29
267
376
309
161
161
267
157
365
471
293
122
96
245
303
195
143
125
146
190
252
416
505
354
154
145
344
699
372
264
277
30
123
144
407
314
322
368
327
124
146
155
305
365
303
192
92
66
298
351
306
322
432
549
222
560
507
714
476
687
211
232
786
1036
2135
1372
437
231
158
170
438
244
246
217
199
125
262
288
305
305
273
113
128
341
984
484
373
340
92
174
242
232
289
367
598
100
62
569
364
356
384
456
134
158
641
462
621
602
171
145
189
390
455
549
184
3093
472
389
1620
1404
2218
1416
1282
325
329
1133
779
867
626
570
275
270
402
908
876
650
527
208
232
566
631
607
479
521
213
316
715
816
2539
1906
888
327
263
802
621
968
670
441
390
247
436
446
2113
1506
811
196
194
443
461
396
743
397
155
152
177
364
447
249
376
144
138
241
792
482
738
1135
201
155
286
236
102
264
241
138
123
464
2231
3477
1271
679
145
161
510
671
530
721
932
313
402
425
811
805
615
585
168
232
1191
831
653
526
295
120
162
469
352
962
1674
429
106
232
500
779
838
430
401
295
350
1252
595
1906
1144
397
837
179
456
377
444
343
271
113
112
559
349
370
234
274
191
155
242
1289
559
352
269
126
145
324
438
740
1307
1034
293
228
214
456
466
562
498
244
209
553
566
714
661
642
250
200
335
416
524
370
407
122
134
318
422
321
366
332
113
335
761
336
263
618
428
158
353
483
284
346
270
333
200
155
715
555
1659
1177
322
303
366
503
439
2229
774
1473
365
221
448
709
561
347
708
233
121
457
546
365
442
288
227
321
361
495
276
834
573
155
194
377
394
423
175
277
183
171
299
575
275
434
451
241
141
401
272
453
284
444
467
105
596
650
506
470
411
250
178
378
561
512
310
407
126
204
173
1226
1037
756
764
158
190
203
941
1461
659
507
204
208
423
420
403
379
698
354
37
186
347
390
1185
467
195
194
614
2502
518
375
467
183
176
376
1375
630
335
374
180
112
493
647
698
1134
663
168
247
1038
792
685
699
797
231
261
336
712
4009
3288
877
533
162
967
1496
474
472
499
208
163
280
238
515
356
111
179
170
451
800
866
917
590
180
224
374
1221
572
779
453
237
158
723
1463
2196
462
564
241
435
4309
2409
977
1822
664
208
283
2395
1191
960
1303
472
219
311
789
579
1699
1443
649
219
138
590
831
693
535
640
406
412
972
747
658
2533
2264
508
286
1058
810
1892
771
618
244
193
842
751
462
1614
502
218
247
423
669
579
596
883
468
202
273
857
1152
1141
777
262
259
1507
1697
1287
1164
1693
289
330
821
1324
1280
826
640
356
189
972
901
656
1302
915
302
311
585
1027
294
893
601
337
366
1591
385
1872
3809
1729
482
659
1273
1185
756
530
500
364
277
1322
1162
847
1321
994
265
177
640
1104
440
582
618
711
367
1051
934
2591
2155
2103
371
302
985
979
103
649
765
225
229
775
545
580
472
471
259
251
565
434
679
514
523
256
213
382
535
2487
522
434
228
185
223
492
382
421
325
209
336
821
833
645
1093
548
191
236
911
888
888
992
795
337
254
612
769
558
584
711
389
175
948
1818
963
555
1016
560
411
1045
981
658
541
502
422
250
529
553
654
596
622
312
588
807
645
862
608
865
234
331
596
1547
2523
2438
2282
438
343
577
668
436
490
543
376
318
1024
759
721
924
5329
677
625
817
1027
786
337
650
368
375
568
611
778
843
520
306
278
459
587
569
622
722
264
219
769
964
581
858
1272
296
350
501
733
599
829
450
256
205
167
432
823
564
547
241
240
195
445
942
1401
203
296
329
1309
734
671
1000
587
321
283
330
517
767
768
480
317
253
499
1072
735
764
653
272
275
590
413
653
712
717
547
350
559
558
1915
2005
962
351
319
546
504
562
388
490
228
289
361
469
697
770
786
455
387
643
548
523
596
585
325
367
473
60
487
762
742
390
462
880
718
1135
801
622
371
356
917
590
1113
886
1184
541
394
895
2614
3338
3023
894
945
968
2937
3133
2081
1771
1203
515
649
958
589
1368
1930
2012
783
586
1366
2080
1437
1199
982
440
438
1163
764
1063
999
1031
1004
589
1352
1225
4726
5619
2307
1084
1223
2491
1404
1523
1526
657
731
884
2041
2219
1639
1381
1275
676
1137
2134
1944
1984
1308
2224
882
657
684
1251
1550
1232
1339
521
781
1382
1714
3954
2260
1358
888
602
1060
3553
2042
1954
1931
1014
1281
2779
2674
1986
2027
2664
914
951
1773
1963
2303
2494
1904
1042
2295
4281
1983
1393
3376
2254
1026
1061
1891
2538
1859
1681
1521
995
1968
2403
2261
1865
899
2281
1377
1356
4705
3508
2819
2171
2199
1384
2028
1455
2694
8050
6198
2678
1595
1330
2102
13519
10017
3060
4979
2512
1861
5979
4868
4749
4739
6963
2350
1962
5850
4345
1772
3195
2980
4709
2082
5246
3431
2892
2491
2609
1248
1270
1276
2915
3105
3452
4246
2221
2099
3286
2814
2882
2332
2662
1296
1544
3700
5453
3224
2629
2192
1521
1941
2374
2163
2561
7464
9601
3902
4081
5764
4488
3043
4258
5360
877
1741
3846
3433
3047
2797
2535
2305
1185
1907
2361
2891
1854
3539
1360
1225
1811
4519
6216
5829
5337
2248
1487
2813
2042
2222
2358
3229
1190
1029
2177
1748
1566
1993
1504
987
995
1683
1421
2069
1924
1098
1245
1062
2084
2001
1558
940
1328
716
815
2509
2017
1641
466
1884
932
930
1946
2337
1358
1943
2785
1135
1126
3209
2602
1912
2286
776
1120
1283
1709
2097
2479
2162
1564
1242
825
1481
743
1674
1670
3037
1434
913
1680
1149
2426
2762
1854
1272
1349
2663
2174
1870
2040
1927
2346
1102
1924
1764
1648
1751
4966
1984
1360
1651
2210
3253
2674
1722
2173
1036
2183
2318
5168
2490
2322
1531
1471
2685
2050
2130
1991
1721
1166
1097
2326
1930
2099
2047
1309
980
999
1217
2076
3584
2939
1946
1096
1165
574
5163
2854
4606
8115
2537
2389
4567
4658
3613
3606
3140
2223
1828
3058
698
3502
3194
5834
2088
1916
2606
3982
3129
3364
2491
1494
1614
3481
2987
3529
3467
2051
428
1640
2475
2118
3223
7167
4166
2419
1891
3315
2485
2213
3327
3692
1696
2355
2420
2489
1104
2259
1541
1872
2728
6834
5182
8024
6446
5847
1813
1565
3695
1116
5023
5725
4875
1696
1412
2084
2111
2261
1816
2311
1101
959
2136
2106
2505
2766
4121
1826
1477
791
5694
6573
6050
4435
1696
1673
2206
3189
3580
3116
3005
1401
1791
2166
3252
2718
3789
2600
1761
1292
2308
4473
5852
2539
2538
2378
1487
2413
2606
2880
2960
2214
1280
860
1825
1932
823
2176
2129
1403
1479
2633
4964
4115
1408
1764
821
1117
1714
1878
2976
1853
1705
2362
1246
1713
2796
2634
2067
1751
2262
1033
2255
598
5231
6057
2661
1303
1437
2541
2704
2063
2112
2140
1675
1002
1832
1693
2104
2138
1654
661
1218
1192
1439
1390
1360
1465
898
1151
1622
2709
847
2769
2839
1411
1232
2152
1749
2259
2365
3619
967
1116
1842
2266
2873
2190
2384
1652
1455
2111
1955
2173
2311
1601
1282
1937
1464
1765
1949
2628
2220
1328
961
2640
2568
1853
2891
2080
1724
880
2326
2310
3249
3545
1924
1279
1129
1588
2297
2477
2183
1442
1282
570
1788
2058
1924
2022
1640
889
979
1920
1583
5829
7428
5412
2916
1638
2559
3178
2401
1666
1554
254
971
2150
1576
2214
3071
2901
1954
1080
2763
2879
3467
2635
2002
1352
1087
2028
2774
2503
2711
8365
3482
488
4756
3864
2760
1335
1639
914
1139
1481
2385
2320
2495
3482
2307
1425
2207
2631
2289
3521
2038
1517
1394
4229
2661
5068
1117
3650
1740
1449
6436
3440
1350
3165
3659
1549
1471
3559
2212
16

In [9]:
data_smedia_sum['total_count_tweet'] = total

In [10]:
data_smedia_sum

,tweet_id,post_date,comment_num,retweet_num,like_num,Subjuctivity,Polarity,Class_sentiment_negative,Class_sentiment_neutral,Class_sentiment_positive,tweet_count,total_count_tweet
date,,,,,,,,,,,,
2015-01-01,5.175966e+19,133490951098,23,42,87,30.276263,12.192172,15,44,35,94,136
2015-01-02,1.113077e+20,286882492028,43,51,136,58.117857,24.628968,25,102,75,202,253
2015-01-03,4.962337e+19,127826282034,10,25,89,19.596165,6.015433,6,58,26,90,115
2015-01-04,6.620679e+19,170445126534,11,35,75,21.760570,7.227273,9,81,30,120,155
2015-01-05,1.523821e+20,392049185482,23,80,201,78.210868,36.700063,17,148,111,276,356
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-28,7.858624e+20,1023818090382,688,900,5253,235.425825,62.305687,112,227,310,649,1549
2019-12-29,7.655246e+20,997058988274,673,839,6425,218.909844,42.348362,130,243,259,632,1471
2019-12-30,1.645430e+21,2142539040171,1494,2201,13014,479.708670,111.280921,235,508,615,1358,3559
2019-12-31,1.364695e+21,1776596925479,936,1086,9674,397.183524,100.569139,193,453,480,1126,2212
2020-01-01,1.697017e+19,22089693639,5,2,19,6.353896,2.944098,1,3,10,14,16

In [11]:
data_smedia_sum.reset_index(inplace = True)
data_smedia_sum

,date,tweet_id,post_date,comment_num,retweet_num,like_num,Subjuctivity,Polarity,Class_sentiment_negative,Class_sentiment_neutral,Class_sentiment_positive,tweet_count,total_count_tweet
0,2015-01-01,5.175966e+19,133490951098,23,42,87,30.276263,12.192172,15,44,35,94,136
1,2015-01-02,1.113077e+20,286882492028,43,51,136,58.117857,24.628968,25,102,75,202,253
2,2015-01-03,4.962337e+19,127826282034,10,25,89,19.596165,6.015433,6,58,26,90,115
3,2015-01-04,6.620679e+19,170445126534,11,35,75,21.760570,7.227273,9,81,30,120,155
4,2015-01-05,1.523821e+20,392049185482,23,80,201,78.210868,36.700063,17,148,111,276,356
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1822,2019-12-28,7.858624e+20,1023818090382,688,900,5253,235.425825,62.305687,112,227,310,649,1549
1823,2019-12-29,7.655246e+20,997058988274,673,839,6425,218.909844,42.348362,130,243,259,632,1471
1824,2019-12-30,1.645430e+21,2142539040171,1494,2201,13014,479.708670,111.280921,235,508,615,1358,3559
1825,2019-12-31,1.364695e+21,1776596925479,936,1086,9674,397.183524,100.569139,193,453,480,1126,2212
1826,2020-01-01,1.697017e+19,22089693639,5,2,19,6.353896,2.944098,1,3,10,14,16

In [ ]:
data_smedia_sum.to_csv('3.tesla_twitter_data_aggregated.csv',index=False)